---
driver:
  name: vagrant
  synced_folders:
    - ['.', '/opt/chef-provisioning-docker']

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
- name: centos-7.1

suites:
- name: default
  run_list:
  - recipe[docker-tests]
  - recipe[docker-tests::create-containers]
  - recipe[docker-tests::change-container-state]
